### ISSUE TITLE
Update readme.md files

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/ResearchSkills#11]
Check that the readme.md files of the practicals 

* Latex
* Literature research
* Stats
* Version control 

provide a good overview on the lab / topic, and links to the relevant files in the subfolders below. I think 

https://github.com/florianhartig/ResearchSkills/tree/master/Labs/LiteratureResearch

is pretty OK, the rest not.

**Comment by florianhartig** [comment]
And maybe also some text in the folder 

https://github.com/florianhartig/ResearchSkills/tree/master/Labs/ProjectOrganization

and in the top folder 

https://github.com/florianhartig/ResearchSkills/tree/master/Labs/

**Comment by shauenstein** [comment]
I need some more information for the ProjectOrganisation readme.

**Comment by florianhartig** [comment]
the idea is simply that this shows how to best organize a quantitative 
research project

* Everything in one folder
* Separation between data, analysis, outcomes, writing

The idea is that they download the template on Friday after the data 
collection, and then they should have all the same folder structure.

The text files in the folders should give some hints regarding 
organization, e.g. the data subfolder could remind them one variable one 
column etc. .. but if you provide an example file that should be clear 
anyway

just that ... in the beginning I didn't think that it's necessary to 
teach people how to use folders to structure their things, but I have 
changed my mind

**Comment by florianhartig** [comment]
ja, die anderen sind ok

**Comment by florianhartig** [comment]
wegen der examle projekt, siehe auch https://github.com/florianhartig/ResearchSkills/issues/12
