### ISSUE TITLE
example projekt optimieren

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/ResearchSkills#12]
Ich habe hier dieses Beispielprojekt https://github.com/florianhartig/ResearchSkills/tree/master/Labs/ProjectOrganization

Dass will ich ihnen am Fr nach der Datenaufnahme geben, und dann soll jeder in dieser Struktur arbeiten

Kannst du bitte 

a) Das top readme.md updaten

b) Das Projekt ueberarbeiten / fuellen? Damit meine ich, e.g. ein beispiel Datensatz in Daten, ein R file in code, das die Daten einliest und einen Output in Results schreibt, ein tex file in thesis dass die Grafik aus results einliest usw

c) Und was dir sonst noch so einfaellt an tips

**Comment by shauenstein** [comment]
If you like what I did, will you close the issue?

**Comment by florianhartig** [comment]
ja, super, danke!
