### ISSUE TITLE
link correction

### ISSUE THREAD

**Issue by elgabbas** [florianhartig/ResearchSkills#17]
Hello Florian,
[this link](https://github.com/florianhartig/ResearchSkills/blob/master/Labs/Statistics/Practicals/StatisticalAnalysisInR/Statistics.Rmd) has a broken link at this line: "These scripts are intended to be read together with the more detailed explanation here"

**Comment by florianhartig** [comment]
Thanks! Severin, can you have a look at that?

**Comment by shauenstein** [comment]
link is corrected. However, in the script there are a few missing figure captions (3.3, 3.4 and 4.1). Would you mind doing these?

**Comment by florianhartig** [comment]
yes, this is already correct I think but I haven't uploaded the final pdf yet because I still do changes.

Thanks
