### ISSUE TITLE
Create proper plots for the lecture on graphics

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/ResearchSkills#18]
The examples that I currently have are of low quality. Need to redo all the figures in R, save in high quality and so on.

Low priority issue for the next years.

**Comment by florianhartig** [comment]
For one part, it's enough if you could simply see that all the figures in the script are nice, proper size, proper labels, etc. 

The other part is - can you go through my lecture and create an R script that re-creates the figures I'm using in the lecture (or the idea of them) in proper R code. 

Doesn't need to be every figure, but there are quite a few figures with poor quality in the script, you will see what I mean, particularly the figures about misleading graphics.

If you're add it, you could also add a few examples about misleading graphics in the stats script, section on visualization. (changing axes, scaling, example with the pie charts)

**Comment by shauenstein** [comment]
I acctually don't really know what you mean. I looked at all the plots, especially the ones about misleading graphics, and they seem fine to me. Or do you mean the size of the excel graphs?
