### ISSUE TITLE
Add multinomial example to the notes

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/ResearchSkills#25]
People had difficulties with the cmlogit function that is currently in appendix the notes.

Add at least one of the two things

* An example on how to transform a normal data frame in the format that cmlogit expects 

* As an alternative, an example using the more simple multinom function, follow this http://www.ats.ucla.edu/stat/r/dae/mlogit.htm

**Comment by shauenstein** [comment]
Where exactly do you say I find the cmlogit? In the appendix of which RS document? I didn't find it in the lecture notes nor in the essential stats. Or is this a misunderstanding and you want me to add it to the appendix of the lecture notes? Thanks!

**Comment by florianhartig** [comment]
Hi, sorry, ich hab die Funktionen verwechselt 
* Im moment ist mlogit im skript, letzter Abschnitt im Appendix. Die Funktion ist allerdings einigermaßen schwer zu bedienen (fand ich zumindest), denn sie erwartet dass der DF für irgendwie so codiert ist dass du für jeden Outcome eine Spalte hast und dann Nullen und Einsen jeweils, wenn ich mich richtig erinner
* Die einfachere Version scheint die Funktion multinom zu sein, in dem Beispiel dass ich oben gelinkt habe

Ich denke es ist schon eine Bemerkung im Skript dass mlogit ein bisschen tricky ist. Vielleicht könntest du ein Beispiel dazufügen wie die daten für mlogit codiert sein müssen, und dann noch ein kleines Beispiel für multinom (kannst du wahrscheinlich beides einfach aus der Hilfe der beiden Funktionen kopieren)
