### ISSUE TITLE
ILIAS updates

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/ResearchSkills#8]
Kannst du auf der ILIAS Seite 

https://ilias.uni-freiburg.de/goto.php?target=crs_441816&client_id=unifreiburg

für 

* Vorlesung
* Übungen

Die Daten aktualisieren (steht alles noch auf 2014), außerdem

* Für jeden Tag die Vorlesungsslides (aber nicht die Materialien) löschen

und ansonsten mal drüberschauen ob alles gut aussieht?

Du solltest schon schreibrechte haben, wenn nicht sag mal Bescheid.

**Comment by shauenstein** [comment]
how can I mark this as "task completed" ?
