### ISSUE TITLE
Transfer graphics to Rmd

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/ResearchSkills#9]
The word file doesn't look very nice and is difficult to maintain - can you create an Rmd that does the same thing? https://github.com/florianhartig/ResearchSkills/tree/master/Labs/Statistics/Practicals/GraphicsInR

**Comment by florianhartig** [comment]
Du muesstest noch die Figures mit hochladen (von der gui)

html files lieber nicht hochladen, das wird zu viel.

**Comment by florianhartig** [comment]
Nach etwas Überlegen hab ich mich gefragt ob man diese Einführung in die R-gui überhaupt brauch ... es ist zwar nicht schlecht wenn sie wissen dass es die gibt, aber andererseits wäre es vielleicht einfacher mit den Leuten direkt in RStudio einzusteigen.

Vielleicht wäre eine gute Lösung die RGui ganz nach hinten zu stellen, so nach dem Motto - das gibt es auch. Was denkst du? Wenn ja könntest du das machen?

**Comment by shauenstein** [comment]
Ich würde das so lassen, ist ja nur eine kurze Einführung. Und außerdem finde ich, sollten die Leute wissen, dass sie eigentlich mit R und nicht mit Rstudio arbeiten. Ich habe schon oft genug gelesen, dass jemand seine Analyse mit Rstudio durchgeführt hat. Meinst du nicht?

**Comment by florianhartig** [comment]
ja, OK, dann lad nur die Figures hoch und lass den rest

**Comment by shauenstein** [comment]
schon passiert!
